### ISSUE TITLE
Doesn't Work with Beta Editor

### ISSUE THREAD

**Issue by noahbuscher** [alanrussian/quizlet-auto-complete#1]
This extension currently does not work with the beta version of Quizlet. Lemme see if I can submit a pull request here for ya...

**Comment by alanrussian** [comment]
Sounds good to me! I'm happy to accept it. I'm excited to see someone actually using this for as little work as I put into it. :-)

**Comment by noahbuscher** [comment]
Yeah! Totally helped me ace my semester tests (and pretty much everyone in my grade uses my cards), and I would have never had the time or patience to fill out the hundreds of vocab terms.

There were a few more changes needed than I originally thought, so I'll probably get around the pushing this weekend. :smile:

**Comment by alanrussian** [comment]
Noah,

I went ahead and fixed this issue. See: 6c63c5467d4288bf8cb57af18f991439bc2a7b91.

I would be happy to fix any other issues you find, please just let me know! :-) Also, please let me know if you still have trouble with the beta editor still. I have pushed the changes to the Chrome Web Store. 

--Alan

**Comment by noahbuscher** [comment]
Oh! Totally spaced this off! Thanks.
